@props(['history'])

@php $hasHistory = count($history) > 0; @endphp

{{-- SECTION 3: Recent Reports. SECTION 4 (empty state) coexists in the DOM
     and is toggled rather than replaced, so a freshly-generated report can
     be prepended into the table and the empty state hidden without a page
     reload — same pattern used by filterable tables elsewhere in the app. --}}
<div class="mt-6 rounded-md border border-sand-200 bg-sand-0 p-5">
    <h2 class="font-display text-base font-bold text-sand-900">Recent Reports</h2>

    <div class="mt-3 overflow-x-auto @if (! $hasHistory) hidden @endif" data-report-history-table>
        <table class="w-full min-w-[640px] text-sm">
            <thead>
                <tr class="border-b border-sand-200 text-left text-xs font-semibold text-sand-500 uppercase">
                    <th class="py-2 pr-2">Report Name</th>
                    <th class="py-2 pr-2">Reporting Period</th>
                    <th class="py-2 pr-2">Generated Date</th>
                    <th class="py-2 pr-2">Generated By</th>
                    <th class="py-2 pr-2"></th>
                </tr>
            </thead>
            <tbody class="divide-y divide-sand-100" id="report-history-body">
                @foreach ($history as $report)
                    <tr>
                        <td class="py-2.5 pr-2 font-medium text-sand-900">{{ $report['name'] }}</td>
                        <td class="py-2.5 pr-2 text-sand-600">{{ $report['range'] }}</td>
                        <td class="py-2.5 pr-2 text-sand-600">{{ \Illuminate\Support\Carbon::parse($report['generatedAt'])->format('M j, Y') }}</td>
                        <td class="py-2.5 pr-2 text-sand-600">{{ $report['generatedBy'] }}</td>
                        <td class="py-2.5 pr-2 text-right">
                            <div class="inline-flex items-center gap-1.5">
                                <button
                                    type="button"
                                    data-view-report
                                    data-type-key="{{ $report['typeKey'] }}"
                                    data-range="{{ $report['range'] }}"
                                    data-generated-at="{{ \Illuminate\Support\Carbon::parse($report['generatedAt'])->format('M j, Y') }}"
                                    data-generated-by="{{ $report['generatedBy'] }}"
                                    class="rounded-sm border border-sand-300 px-3 py-1.5 text-xs font-semibold text-sand-800 hover:border-primary-300"
                                >
                                    View
                                </button>
                                <button type="button" data-toast-trigger data-toast-message="Downloading {{ $report['name'] }}..." class="rounded-sm border border-sand-300 px-3 py-1.5 text-xs font-semibold text-sand-800 hover:border-primary-300">
                                    Download
                                </button>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <x-dashboard.empty-state
        data-report-history-empty
        @class(['mt-3', 'hidden' => $hasHistory])
        icon="ti-file-report"
        title="No reports generated yet."
        description="Select a report type and reporting period above to generate a report."
    />
</div>
